from tkinter import *

def main():    
    frame_select_startLang.place(x = 30, y = 30)
    startLang_radioBtn_kor.pack()
    startLang_radioBtn_eng.pack()
    startLang_radioBtn_ch.pack()

    frame_select_arrLang.place(x = 160, y = 30)
    arrLang_checkBtn_reTL.grid(row = 0, column = 0)
    arrLang_checkBtn_Eng.grid(row = 0, column = 1)
    arrLang_checkBtn_Ch.grid(row = 0, column = 2) 
    arrLang_checkBtn_Jp.grid(row = 1, column = 0) 
    arrLang_checkBtn_Spain.grid(row = 1, column = 1)
    arrLang_checkBtn_France.grid(row = 1, column = 2) 
    arrLang_checkBtn_Germany.grid(row = 2, column = 0)
    arrLang_checkBtn_Vietnam.grid(row = 2, column = 1)
    arrLang_checkBtn_Indonesia.grid(row = 2, column = 2) 
    arrLang_checkBtn_Laos.grid(row = 3, column = 0) 
    arrLang_checkBtn_Thailand.grid(row = 3, column = 1)
    arrLang_checkBtn_Brazil.grid(row = 3, column = 2) 
    arrLang_checkBtn_All.grid(row = 4, column = 0) 

    root.mainloop()

if __name__ == '__main__':
    root = Tk()
    root.title('ooo')
    root.geometry('460x320')
    
    frame_select_startLang = LabelFrame(root, text = 'Start Language')
    startLang_var = IntVar()
    startLang_radioBtn_kor = Radiobutton(frame_select_startLang, text = 'Korean', value = 1, variable = startLang_var)
    startLang_radioBtn_eng = Radiobutton(frame_select_startLang, text = 'English', value = 2, variable = startLang_var)
    startLang_radioBtn_ch = Radiobutton(frame_select_startLang, text = 'Chineses', value = 3, variable = startLang_var)
    
    frame_select_arrLang = LabelFrame(root, text = 'Result Language') # borderwidth = 상수: 라벨 프레임 두께
    arrLang_var_reTL = IntVar() 
    arrLang_var_Eng = IntVar() 
    arrLang_var_Ch = IntVar() 
    arrLang_var_Jp = IntVar() 
    arrLang_var_Spain = IntVar() 
    arrLang_var_France = IntVar() 
    arrLang_var_Germany = IntVar()
    arrLang_var_Vietnam = IntVar()
    arrLang_var_Indonesia = IntVar() 
    arrLang_var_Laos = IntVar() 
    arrLang_var_Thailand = IntVar() 
    arrLang_var_Brazil = IntVar() 
    arrLang_var_All = IntVar() 
    arrLang_checkBtn_reTL = Checkbutton(frame_select_arrLang, text = 'Re-Translate', variable = arrLang_var_reTL)
    arrLang_checkBtn_Eng = Checkbutton(frame_select_arrLang, text = 'English', variable = arrLang_var_Eng)
    arrLang_checkBtn_Ch = Checkbutton(frame_select_arrLang, text = 'Chinese', variable = arrLang_var_Ch)
    arrLang_checkBtn_Jp = Checkbutton(frame_select_arrLang, text = 'Japanese', variable = arrLang_var_Jp)
    arrLang_checkBtn_Spain = Checkbutton(frame_select_arrLang, text = 'Spain', variable = arrLang_var_Spain)
    arrLang_checkBtn_France = Checkbutton(frame_select_arrLang, text = 'France', variable = arrLang_var_France)
    arrLang_checkBtn_Germany = Checkbutton(frame_select_arrLang, text = 'Germany', variable = arrLang_var_Germany)
    arrLang_checkBtn_Vietnam = Checkbutton(frame_select_arrLang, text = 'Vietnam', variable = arrLang_var_Vietnam)
    arrLang_checkBtn_Indonesia = Checkbutton(frame_select_arrLang, text = 'Indonesia', variable = arrLang_var_Indonesia)
    arrLang_checkBtn_Laos = Checkbutton(frame_select_arrLang, text = 'Laos', variable = arrLang_var_Laos)
    arrLang_checkBtn_Thailand = Checkbutton(frame_select_arrLang, text = 'Thailand', variable = arrLang_var_Thailand)
    arrLang_checkBtn_Brazil = Checkbutton(frame_select_arrLang, text = 'Brazil', variable = arrLang_var_Brazil)
    arrLang_checkBtn_All = Checkbutton(frame_select_arrLang, text = 'All Lnaguages', variable = arrLang_var_All)

    main()